### ISSUE TITLE
how to combined call api webservice and web-worker

### ISSUE THREAD

**Issue by ducvietsqt** [AlbertLucianto/vuex-search#11]
Look great for start! but i have a question for result:
- If i want can get result from api web service, It can does this?
- Please let me know how to add call api service combined in that
Thanks.

**Comment by AlbertLucianto** [comment]
@ducvietsqt vuex-search works for client-side search using web workers, hence there should be no relation with retrieving result from api web service. Please reopen if I misunderstood anything.
