### ISSUE TITLE
Multiple resources not working

### ISSUE THREAD

**Issue by pjhile** [AlbertLucianto/vuex-search#9]
When using multiple resources only the first one seems to get indexed and has it's isSearching promise resolved.

![resources](https://user-images.githubusercontent.com/224067/51784067-a94bf980-2111-11e9-90a8-93a213835542.png)

![store](https://user-images.githubusercontent.com/224067/51784070-acdf8080-2111-11e9-83b1-fb522297d2c8.png)

**Comment by AlbertLucianto** [comment]
@pjhile thanks for raising the issue. This should be fixed in v2.2.4.
